status=error
name=SparkLog4j2

appender.console.type=Console
appender.console.name=console
appender.console.target=SYSTEM_OUT
appender.console.layout.type=PatternLayout
appender.console.layout.pattern=%d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n

rootLogger.level=INFO
rootLogger.appenderRefs=console
rootLogger.appenderRef.console.ref=console

logger.fdi.name=com.oracle.fdi.datashare
logger.fdi.level=INFO
logger.fdi.additivity=false
logger.fdi.appenderRefs=console
logger.fdi.appenderRef.console.ref=console

logger.config1.name=org.apache.spark.repl.SparkIMain$exprTyper
logger.config1.level=WARN

logger.config2.name=org.apache.spark.repl.SparkILoop$SparkILoopInterpreter
logger.config2.level=WARN

logger.config3.name=org.sparkproject.jetty
logger.config3.level=WARN

logger.config4.name=com.oracle.pic
logger.config4.level=WARN

logger.config5.name=org.apache.spark
logger.config5.level=WARN

logger.config6.name=org.apache.iceberg
logger.config6.level=WARN

logger.config7.name=org.apache.hadoop
logger.config7.level=WARN

logger.config8.name=org.apache.parquet.hadoop
logger.config8.level=WARN
